package com.wy.moodindex.pojo;

public class Stock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_id
     *
     * @mbg.generated
     */
    private String stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stockcol
     *
     * @mbg.generated
     */
    private String stockcol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.stock_name
     *
     * @mbg.generated
     */
    private String stockName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated
     */
    public Stock(Integer id, String stockId, String stockcol, String stockName) {
        this.id = id;
        this.stockId = stockId;
        this.stockcol = stockcol;
        this.stockName = stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbg.generated
     */
    public Stock() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_id
     *
     * @return the value of stock.stock_id
     *
     * @mbg.generated
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_id
     *
     * @param stockId the value for stock.stock_id
     *
     * @mbg.generated
     */
    public void setStockId(String stockId) {
        this.stockId = stockId == null ? null : stockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stockcol
     *
     * @return the value of stock.stockcol
     *
     * @mbg.generated
     */
    public String getStockcol() {
        return stockcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stockcol
     *
     * @param stockcol the value for stock.stockcol
     *
     * @mbg.generated
     */
    public void setStockcol(String stockcol) {
        this.stockcol = stockcol == null ? null : stockcol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.stock_name
     *
     * @return the value of stock.stock_name
     *
     * @mbg.generated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.stock_name
     *
     * @param stockName the value for stock.stock_name
     *
     * @mbg.generated
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }
}